# user key:
# 1. mkdir -p ~/.config/sops/age
# 2. age-keygen -o ~/.config/sops/age/keys.txt
# 3. chmod 600 ~/.config/sops/age/keys.txt
# 4. age-keygen -y ~/.config/sops/age/keys.txt

# host key:
# 1. ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub

# recrypt after adding new keys to the file
# 1. sops updatekeys secrets.yaml

# add to secrets:
# sops secrets/secrets.yaml

keys:
  - &dominic-egginton C11BEB9007709C34FABBB5314C79CE4F82847A9F
  - &latitude-7390 6950afb09db6de78a00d83f61a99b41e26cad84d
  - &ghost-gs60 92e45e7f54367570bffead039366e5e7de22c73c
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - pgp:
      - *dominic-egginton

      - *latitude-7390
      - *ghost-gs60
