name: Install Nix
description: Install Nix package manager, optionally freeing disk space from the runner first.

inputs:
  free-disk-space:
    description: "Free disk space"
    default: false

runs:
  using: "composite"
  steps:
    - name: free-disk-space
      if: ${{ inputs.free-disk-space == 'true' && runner.os == 'Linux' && runner.arch == 'x64' }}
      run: |
        sudo apt clean
        docker image prune -af
        sudo apt-get remove -y azure-cli google-cloud-cli google-cloud-cli-anthoscli
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/share/dotnet/
      shell: bash
    - name: Install Nix
      uses: cachix/install-nix-action@v31
