name: Free Disk Space
description: Free up disk space on runner 
runs:
  using: "composite"
  steps:
    - name: free-disk-space
      if: ${{ runner.os == 'Linux' && runner.arch == 'x64' }}
      run: | 
        sudo apt clean
        docker image prune -af
        sudo apt-get remove -y azure-cli google-cloud-cli google-cloud-cli-anthoscli
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/share/dotnet/
      shell: bash 