name: Free Disk Space
description: Free up disk space on runner 
runs:
  using: "composite"
  steps:
    - name: free-disk-space
      run: ./github/actions/free-disk-space/free-disk-space.sh
      shell: bash 
