[project]
name = "dominicegginton-personal"
revision = "1.0"

[providers]
secrets = "gcsm://dominicegginton-personal"

[profiles.default]
TF_VAR_tailscale_api_key = { description = "Tailscale API key", ref = { item = "tailscale_api_key" }, providers = ["secrets"] }
TF_VAR_tailscale_tailnet = { description = "Tailscale Tailnet", ref = { item = "tailscale_tailnet" }, providers = ["secrets"] }
