[project]
name = "dominicegginton-personal"
revision = "1.0"
require_reason = false

[providers]
secrets = "gcsm://dominicegginton-personal"

[profiles.default]
TF_VAR_tailscale_api_key = { description = "Tailscale API key", providers = ["secrets"] }
TF_VAR_tailscale_tailnet = { description = "Tailscale Tailnet", providers = ["secrets"] }
TF_VAR_nextdns_api_token = { description = "Nextdns", providers = ["secrets"] }
TF_VAR_nextdns_profile_ribble = { description = "NextDNS Profile ID for Ribble", providers = ["secrets"] }
TF_VAR_nextdns_profile_quandon = { description = "NextDNS Profile ID for Quandon", providers = ["secrets"] }
TF_VAR_cloudflare_api_token = { description = "Cloudflare API Token", providers = ["secrets"] }
TF_VAR_cloudflare_account_id = { description = "Cloudflare Account ID", providers = ["secrets"] }
TF_VAR_cloudflare_zone_id = { description = "Cloudflare Zone ID for dominicegginton.dev", providers = ["secrets"] }
