[project]
name = "dominicegginton-personal"
revision = "1.0"
require_reason = false

[providers]
secrets = "gcsm://dominicegginton-personal"

[profiles.default]
TF_VAR_tailscale_api_key = { description = "Tailscale API key", providers = ["secrets"] }
TF_VAR_tailscale_tailnet = { description = "Tailscale Tailnet", providers = ["secrets"] }
TF_VAR_tailscale_dns_address = { description = "Tailscale DNS Address", providers = ["secrets"] }
